[libraries]
config = { module = "common:config" }
json = { module = "common:json" }
logging = { module = "common:logging" }
model = { module = "common:model" }
db-target = { module = "common:target-db" }
util = { module = "common:util" }
stack-io = { module = "common:stack-io" }
