name: Build Core Server

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request_target:
    branches:
    - main
    - dev
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    paths:
    - 'project/common/**'
    - 'project/core/**'
    - 'project/conventions/**'
    - 'gradle/common.versions.toml'
    - 'gradle/libs.versions.toml'

jobs:
  gradle-build:
    name: Pull Request Build Verification
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-core-server
      with:
        gh-token: ${{ secrets.GH_TOKEN }}
        gh-user: ${{ secrets.GH_USERNAME }}
